### PR TITLE
Added localization support, added fadein onload for background image, improved code

### PR DESCRIPTION
**Pull request by deansheather**

### CODE REVIEW

**Comment by deansheather** [comment]
Preview URL: https://deansheather.github.io/homepage

**Comment by AlexFlipnote** [comment]
Could this be in 24h system? or at least have 24h as default and the option to change to AM/PM

**Comment by TTtie** [comment]
yes plz, some countries don't use AM/PM system

**Comment by deansheather** [comment]
Localization support means that the time is displayed in the client's language and their region's preferred time format.

**Comment by deansheather** [comment]
So your regions preferred time format is 12hr time. I can look into making it switchable if you like.

**Comment by AlexFlipnote** [comment]
Yeah, having it switchable would be good, I live in Norway and we use 24h

**Comment by deansheather** [comment]
Strange, I'll look into it.

**Comment by TTtie** [comment]
uhhhh.... btw will look into firefox and will report bugs here if any

**Comment by AlexFlipnote** [comment]
Seems fair

**Pull request merged**
