### PR TITLE
Firefox compatibility

### PR DESCRIPTION
**Pull request by TTtie**
Updated the website;
Actual changes are:

- changed to native javascript for choosing backgrounds
- fixed Firefox incompatibility (Image should now stretch on all browsers); compare [here](https://i.tttie.ga/2016-11-19_20-03-18.jpg)
- and some more stuff; (code changes etc.)

I don't know how to describe this commit anymore,
By the way, hope this will be merged!
~TTtie

### CODE REVIEW

**Comment by TTtie** [comment]
yes ik 2 much commits; testing shit-code

**Comment by TTtie** [comment]
live showcase of the edit is [here](https://tttie.github.io/homepage)

**Comment by AlexFlipnote** [comment]
You can edit the footer and replace it inside the README, then I merge the commits

**Comment by TTtie** [comment]
Uhh what do you mean? Revert the footer back or just leave them and add them at README?

**Comment by AlexFlipnote** [comment]
I'll fix it for you instead, don't worry

**Pull request merged**
