### PR TITLE
Change domain responsible for scrapping favicons

### PR DESCRIPTION
**Pull request by mic0ishere**

### CODE REVIEW

**Comment by AlexFlipnote** [comment]
Don't really wish to use a herokuapp for this.

**Comment by mic0ishere** [comment]
> Don't really wish to use a herokuapp for this.

But are there any better alternatives right now?

**Comment by mic0ishere** [comment]
Alternatively, use Google S2 - https://stackoverflow.com/a/61326376

**Comment by AlexFlipnote** [comment]
Think I'll use the Google one instead

**Comment by mic0ishere** [comment]
Unfortunately, I discovered an issue with it - it sometimes doesn't work. Try putting `github.com` as domain

**Comment by AlexFlipnote** [comment]
Eh fair enough

**Pull request merged**
